server:
  port: 8082

spring:
    rabbitmq:
            host: ip
            port: 5672
            username: dev_1
            password: dev_1
            virtual-host: /
            publisher-confirms: true
