server:
  port: 8081

#数据源
spring:
      application.name: springboot-rabbitmq
      rabbitmq:
          host: ip
          port: 5672
          username: dev_1
          password: dev_1
          virtual-host: /
          publisher-confirms: true


